### ISSUE TITLE
Run bpmn-js and form-js in same Angular project

### ISSUE THREAD

**Issue by SeanAda** [bpmn-io/form-js#309]
__Describe the Bug__

I want to use the bpmn-js editor und form-js editor in the same Angular project.
It it possible to use both in seperate fashion, but it is not possible to build and run it, if both are imported.

I got the following stacktrace:

```
bpmn-modeler.production.min.js:7 unhandled error in event listener TypeError: Cannot read properties of undefined (reading '__H')
    at d (hooks:1:150)
    at y (hooks:1:286)
    at p (hooks:1:250)
    at p.BpmnPropertiesPanel [as constructor] (index.esm.js:1496:37)
    at p.M [as render] (preact.module.js:1:8038)
    at I (preact.module.js:1:5744)
    at m (preact.module.js:1:2155)
    at I (preact.module.js:1:5907)
    at N (preact.module.js:1:8095)
    at BpmnPropertiesPanelRenderer._render (index.esm.js:1793:11)

Un._invokeListener @ bpmn-modeler.production.min.js:7
2core.js:6498 ERROR TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, ReadableStream, Array, AsyncIterable, or Iterable.
    at createInvalidObservableTypeError (throwUnobservableError.js:2:1)
    at innerFrom (from.js:41:43)
    at catchError.js:10:38
    at OperatorSubscriber._this._error (OperatorSubscriber.js:21:1)
    at Subscriber.error (Subscriber.js:42:1)
    at tap.js:20:1
    at OperatorSubscriber._this._error (OperatorSubscriber.js:21:1)
    at Subscriber.error (Subscriber.js:42:1)
    at from.js:68:47
    at _ZoneDelegate.invoke (zone.js:372:1)
```

It seems like this is an issue triggered by using same functions or functions, which are named the same.

__Steps to Reproduce__

1. Install both deps via npm
2. Import and use both editor ate the same time.
3. Open the used component in Browser

__Environment__

- form-js 0.7.2
- bpmn-js 9.3.2
- bpmn-js-properties-panel 1.4.0

**Comment by pinussilvestrus** [comment]
@SeanAda any updates on this one?
