### ISSUE TITLE
Add node/npm version compatibility to readme

### ISSUE THREAD

**Issue by jonathanlukas** [bpmn-io/form-js#327]
__Is your feature request related to a problem? Please describe__

When I check out the project to run the playground for example, I am not sure which version of node and npm is used to build the project.

__Describe the solution you'd like__

The readme should contain information about either one definitive version this current state is built with or a version compatibility matrix. The matrix is more complex, so I guess the first option will be good enough.

__Describe alternatives you've considered__

A more handsome approach would of course be programmatic version setting (a script, some kind of backwards-compatiblity-check?). I am not sure whether this is part of npm. From what I have seen, npm is version-bound to node.

__Additional context__

**Comment by nikku** [comment]
Which issue did you encounter building it with the latest Node/npm version?

**Comment by jonathanlukas** [comment]
I will try to reproduce and provide you with a log

**Comment by jonathanlukas** [comment]
Node: `18.9.0`
npm: `8.19.1`

```
npm run start:playground                                                                                                                                                                                                                                                                                                                                                                                                                          ✔ 

> start:playground
> npm run start:pkg -- @bpmn-io/form-js-playground


> start:pkg
> cross-env SINGLE_START=basic npm run dev -- @bpmn-io/form-js-playground


> dev
> run-s build "lerna-dev -- {@}" -- @bpmn-io/form-js-playground


> build
> lerna run build --sort --stream

lerna notice cli v5.5.0
lerna info Executing command in 4 packages: "npm run build"
@bpmn-io/form-js-viewer: > @bpmn-io/form-js-viewer@0.8.0 build
@bpmn-io/form-js-viewer: > run-p bundle generate-types
@bpmn-io/form-js-viewer: > @bpmn-io/form-js-viewer@0.8.0 bundle
@bpmn-io/form-js-viewer: > rollup -c --failAfterWarnings
@bpmn-io/form-js-viewer: > @bpmn-io/form-js-viewer@0.8.0 generate-types
@bpmn-io/form-js-viewer: > tsc --allowJs --skipLibCheck --declaration --emitDeclarationOnly --outDir dist/types src/index.js && cp src/*.d.ts dist/types
@bpmn-io/form-js-viewer: src/index.js → dist/index.cjs, dist/index.es.js...
@bpmn-io/form-js-viewer: created dist/index.cjs, dist/index.es.js in 2s
@bpmn-io/form-js-editor: > @bpmn-io/form-js-editor@0.8.0 build
@bpmn-io/form-js-editor: > run-p bundle generate-types
@bpmn-io/form-js-editor: > @bpmn-io/form-js-editor@0.8.0 bundle
@bpmn-io/form-js-editor: > rollup -c --failAfterWarnings
@bpmn-io/form-js-editor: > @bpmn-io/form-js-editor@0.8.0 generate-types
@bpmn-io/form-js-editor: > tsc --allowJs --skipLibCheck --declaration --emitDeclarationOnly --outDir dist/types src/index.js && cp src/**.d.ts dist/types
@bpmn-io/form-js-editor: src/index.js → dist/index.cjs, dist/index.es.js...
@bpmn-io/form-js-editor: created dist/index.cjs, dist/index.es.js in 2.3s
@bpmn-io/form-js-playground: > @bpmn-io/form-js-playground@0.8.0 build
@bpmn-io/form-js-playground: > run-p bundle generate-types
@bpmn-io/form-js-playground: > @bpmn-io/form-js-playground@0.8.0 bundle
@bpmn-io/form-js-playground: > rollup -c --failAfterWarnings
@bpmn-io/form-js-playground: > @bpmn-io/form-js-playground@0.8.0 generate-types
@bpmn-io/form-js-playground: > tsc --allowJs --skipLibCheck --declaration --emitDeclarationOnly --outDir dist/types src/index.js
@bpmn-io/form-js-playground: src/index.js → dist/index.cjs, dist/index.es.js...
@bpmn-io/form-js-playground: created dist/index.cjs, dist/index.es.js in 2.1s
@bpmn-io/form-js-playground: src/index.js → dist/form-playground.umd.js...
@bpmn-io/form-js-playground: created dist/form-playground.umd.js in 3.8s
@bpmn-io/form-js: > @bpmn-io/form-js@0.8.0 build
@bpmn-io/form-js: > run-p bundle generate-types
@bpmn-io/form-js: > @bpmn-io/form-js@0.8.0 bundle
@bpmn-io/form-js: > rollup -c --failAfterWarnings
@bpmn-io/form-js: > @bpmn-io/form-js@0.8.0 generate-types
@bpmn-io/form-js: > tsc --allowJs --skipLibCheck --declaration --emitDeclarationOnly --removeComments --outDir dist/types src/index.js
@bpmn-io/form-js: src/index.js → dist/index.cjs, dist/index.es.js...
@bpmn-io/form-js: created dist/index.cjs, dist/index.es.js in 49ms
@bpmn-io/form-js: src/editor.js → ./dist/form-editor.umd.js...
@bpmn-io/form-js: created ./dist/form-editor.umd.js in 1.1s
@bpmn-io/form-js: src/viewer.js → ./dist/form-viewer.umd.js...
@bpmn-io/form-js: created ./dist/form-viewer.umd.js in 243ms
@bpmn-io/form-js: src/playground.js → ./dist/form-playground.umd.js...
@bpmn-io/form-js: created ./dist/form-playground.umd.js in 1.4s
lerna success run Ran npm script 'build' in 4 packages in 20.8s:
lerna success - @bpmn-io/form-js-editor
lerna success - @bpmn-io/form-js-playground
lerna success - @bpmn-io/form-js-viewer
lerna success - @bpmn-io/form-js

> lerna-dev
> lerna run dev --stream --scope @bpmn-io/form-js-playground

lerna notice cli v5.5.0
lerna notice filter including "@bpmn-io/form-js-playground"
lerna info filter [ '@bpmn-io/form-js-playground' ]
lerna info Executing command in 1 package: "npm run dev"
@bpmn-io/form-js-playground: > @bpmn-io/form-js-playground@0.8.0 dev
@bpmn-io/form-js-playground: > npm test -- --auto-watch --no-single-run
@bpmn-io/form-js-playground: > @bpmn-io/form-js-playground@0.8.0 test
@bpmn-io/form-js-playground: > karma start --auto-watch --no-single-run
@bpmn-io/form-js-playground: 19 09 2022 13:14:12.950:INFO [preprocessor.env]: Publishing variables:  [ 'SINGLE_START' ]
@bpmn-io/form-js-playground: Webpack bundling...
@bpmn-io/form-js-playground: Webpack starts watching...
@bpmn-io/form-js-playground: 19 09 2022 13:14:14.035:ERROR [karma-server]: UnhandledRejection: Error: error:0308010C:digital envelope routines::unsupported
@bpmn-io/form-js-playground:     at new Hash (node:internal/crypto/hash:71:19)
@bpmn-io/form-js-playground:     at Object.createHash (node:crypto:133:10)
@bpmn-io/form-js-playground:     at BulkUpdateDecorator.hashFactory (/Users/jonathanlukas/git/camunda/form-js/node_modules/webpack/lib/util/createHash.js:145:18)
@bpmn-io/form-js-playground:     at BulkUpdateDecorator.update (/Users/jonathanlukas/git/camunda/form-js/node_modules/webpack/lib/util/createHash.js:46:50)
@bpmn-io/form-js-playground:     at SourceMapSource.updateHash (/Users/jonathanlukas/git/camunda/form-js/node_modules/webpack-sources/lib/SourceMapSource.js:233:8)
@bpmn-io/form-js-playground:     at NormalModule._initBuildHash (/Users/jonathanlukas/git/camunda/form-js/node_modules/webpack/lib/NormalModule.js:868:17)
@bpmn-io/form-js-playground:     at handleParseResult (/Users/jonathanlukas/git/camunda/form-js/node_modules/webpack/lib/NormalModule.js:934:10)
@bpmn-io/form-js-playground:     at /Users/jonathanlukas/git/camunda/form-js/node_modules/webpack/lib/NormalModule.js:1026:4
@bpmn-io/form-js-playground:     at processResult (/Users/jonathanlukas/git/camunda/form-js/node_modules/webpack/lib/NormalModule.js:743:11)
@bpmn-io/form-js-playground:     at /Users/jonathanlukas/git/camunda/form-js/node_modules/webpack/lib/NormalModule.js:807:5
@bpmn-io/form-js-playground: 19 09 2022 13:14:14.035:ERROR [karma-server]: Error: error:0308010C:digital envelope routines::unsupported
@bpmn-io/form-js-playground:     at new Hash (node:internal/crypto/hash:71:19)
@bpmn-io/form-js-playground:     at Object.createHash (node:crypto:133:10)
@bpmn-io/form-js-playground:     at BulkUpdateDecorator.hashFactory (/Users/jonathanlukas/git/camunda/form-js/node_modules/webpack/lib/util/createHash.js:145:18)
@bpmn-io/form-js-playground:     at BulkUpdateDecorator.update (/Users/jonathanlukas/git/camunda/form-js/node_modules/webpack/lib/util/createHash.js:46:50)
@bpmn-io/form-js-playground:     at SourceMapSource.updateHash (/Users/jonathanlukas/git/camunda/form-js/node_modules/webpack-sources/lib/SourceMapSource.js:233:8)
@bpmn-io/form-js-playground:     at NormalModule._initBuildHash (/Users/jonathanlukas/git/camunda/form-js/node_modules/webpack/lib/NormalModule.js:868:17)
@bpmn-io/form-js-playground:     at handleParseResult (/Users/jonathanlukas/git/camunda/form-js/node_modules/webpack/lib/NormalModule.js:934:10)
@bpmn-io/form-js-playground:     at /Users/jonathanlukas/git/camunda/form-js/node_modules/webpack/lib/NormalModule.js:1026:4
@bpmn-io/form-js-playground:     at processResult (/Users/jonathanlukas/git/camunda/form-js/node_modules/webpack/lib/NormalModule.js:743:11)
@bpmn-io/form-js-playground:     at /Users/jonathanlukas/git/camunda/form-js/node_modules/webpack/lib/NormalModule.js:807:5 {
@bpmn-io/form-js-playground:   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
@bpmn-io/form-js-playground:   library: 'digital envelope routines',
@bpmn-io/form-js-playground:   reason: 'unsupported',
@bpmn-io/form-js-playground:   code: 'ERR_OSSL_EVP_UNSUPPORTED'
@bpmn-io/form-js-playground: }
@bpmn-io/form-js-playground: Webpack stopped watching.
@bpmn-io/form-js-playground: npm ERR! Lifecycle script `test` failed with error: 
@bpmn-io/form-js-playground: npm ERR! Error: command failed 
@bpmn-io/form-js-playground: npm ERR!   in workspace: @bpmn-io/form-js-playground@0.8.0 
@bpmn-io/form-js-playground: npm ERR!   at location: /Users/jonathanlukas/git/camunda/form-js/packages/form-js-playground 
@bpmn-io/form-js-playground: npm ERR! Lifecycle script `dev` failed with error: 
@bpmn-io/form-js-playground: npm ERR! Error: command failed 
@bpmn-io/form-js-playground: npm ERR!   in workspace: @bpmn-io/form-js-playground@0.8.0 
@bpmn-io/form-js-playground: npm ERR!   at location: /Users/jonathanlukas/git/camunda/form-js/packages/form-js-playground 
lerna ERR! npm run dev exited 1 in '@bpmn-io/form-js-playground'
ERROR: "lerna-dev -- \@bpmn-io/form-js-playground" exited with 1.
```

**Comment by nikku** [comment]
See https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported. 

My personal recommendation is: Do not surf the bleeding edge, but use Node LTS.

**Comment by nikku** [comment]
See also [this thread](https://github.com/webpack/webpack/issues/14532).

Hundreds of users experience this issue, caused by breaking hashing support with Node@18.
