### ISSUE TITLE
Compatibility issue between ESM and CommonJS modules

### ISSUE THREAD

**Issue by guilhermep** [bpmn-io/form-js#628]
I'm encountering an issue while trying to wrap `@bpmn-io/form-js-viewer` inside a React component due to a compatibility problem between ECMAScript modules (ESM) and CommonJS modules from a dependency.

My component:

```
import React, { useRef, useEffect } from 'react';
import { Form } from '@bpmn-io/form-js-viewer';

interface FormJSViewerProps {
  schema: object;
  data?: object;
  onSubmit?: (event: any) => void;
  onChanged?: (event: any) => void;
  onChangedPriority?: number;
}

const FormJSViewer: React.FC<FormJSViewerProps> = ({
  schema,
  data,
  onSubmit,
  onChanged,
  onChangedPriority = 500,
}) => {
  const containerRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    if (!containerRef.current) return;

    const form = new Form({
      container: containerRef.current
    });

    (async () => {
      await form.importSchema(schema, data);
    })();

    if (onSubmit) {
      form.on('submit', onSubmit);
    }

    if (onChanged) {
      form.on('changed', onChangedPriority, onChanged);
    }

    return () => {
      // Clean up on unmount
      form.destroy();
    };
  }, [containerRef, schema, data, onSubmit, onChanged, onChangedPriority]);

  return <div ref={containerRef}></div>;
};

export default FormJSViewer;

```

When trying to use the component, I encounter the following error message:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/guilhermedepaula/git/woodmin/node_modules/feelin/dist/index.js from /Users/guilhermedepaula/git/woodmin/node_modules/@bpmn-io/form-js-viewer/dist/index.cjs not supported.
index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/guilhermedepaula/git/woodmin/node_modules/feelin/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at Object.<anonymous> (/Users/guilhermedepaula/git/woodmin/node_modules/@bpmn-io/form-js-viewer/dist/index.cjs:5:14)
    at Object.<anonymous> (/Users/guilhermedepaula/git/woodmin/build/index.js:18631:65)
    at /Users/guilhermedepaula/git/woodmin/node_modules/@remix-run/serve/dist/index.js:43:17
    at Layer.handle [as handle_request] (/Users/guilhermedepaula/git/woodmin/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/guilhermedepaula/git/woodmin/node_modules/express/lib/router/route.js:144:13)
    at next (/Users/guilhermedepaula/git/woodmin/node_modules/express/lib/router/route.js:140:7)
    at next (/Users/guilhermedepaula/git/woodmin/node_modules/express/lib/router/route.js:140:7)
...
```
As per the error message, it seems there is an issue with the `feelin` package being treated as an ES module while it's being `require()`d from a CommonJS module in the `@bpmn-io/form-js-viewer` package, which is not supported.

Could you please provide guidance on how to resolve this compatibility issue or consider updating the package to address this problem? Any suggestions for temporary workarounds would also be appreciated.

### Environment

- Host (Browser/Node version), if applicable: Node v18.16.0
- OS: MacOS Ventura
- Library version: 0.14.1

**Comment by guilhermep** [comment]
After further inspection I discovered this is an [issue with Remix's bundler](https://remix.run/docs/en/1.15.0/pages/gotchas#importing-esm-packages).
