### ISSUE TITLE
Unit Tests Fails Because of Date Mismatch Errors in form-js-viewer

### ISSUE THREAD

**Issue by guilhermep** [bpmn-io/form-js#659]
### Describe the Bug

Several unit tests related to date and time processing are failing. The tests are expecting certain dates to be returned, but the actual returned dates are off by one day. This problem is happening in multiple tests.

### Steps to Reproduce

1. Clone the repo
2. Checkout the latest release with `git checkout v0.14.1`
3. Run `npm install` and `npm run all`
4. The following output is shown:
``` 
... 
     LOG: 'Form <changed>', InternalEvent{initialData: Object{creditor: 'John Doe Company', amount: 456, invoiceNumber: 'C-123', approved: true, approvedBy: 'John Doe', mailto: [..., ...], product: 'camunda-cloud', tags: [..., ..., ...], language: 'english', documents: [..., ...], approverComments: '', conversation: null}, data: Object{creditor: 'John Doe Company', amount: 456, invoiceNumber: 'C-123', approved: true, approvedBy: 'John Doe', mailto: [..., ...], product: 'camunda-cloud', tags: [..., ..., ...], language: 'english', documents: [..., ...], approverComments: '', conversation: null}, properties: Object{}, errors: Object{}, schema: Object{components: [..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ...], type: 'default', id: 'default1'}, type: 'changed'}
       Chrome Headless 109.0.5412.0 (Mac OS 10.15.7) Datetime (date) should render value FAILED
        AssertionError: expected '11/12/1996' to equal '11/13/1996'
            at Context.eval (webpack-internal:///./test/spec/render/components/form-fields/Datetime.spec.js:71:37)
       Chrome Headless 109.0.5412.0 (Mac OS 10.15.7) Datetime (date) should render disabled FAILED
        AssertionError: expected '11/12/1996' to equal '11/13/1996'
            at Context.eval (webpack-internal:///./test/spec/render/components/form-fields/Datetime.spec.js:85:37)
       Chrome Headless 109.0.5412.0 (Mac OS 10.15.7) Datetime (date) should disable dates prior to 1900 FAILED
        AssertionError: expected [ 'flatpickr-prev-month' ] to include 'flatpickr-disabled'
            at Context.eval (webpack-internal:///./test/spec/render/components/form-fields/Datetime.spec.js:309:53)
       Chrome Headless 109.0.5412.0 (Mac OS 10.15.7) DateTimeUtil #serializeDateTime should serialize with full timezone FAILED
        AssertionError: expected '1995-11-14T00:00-02:00' to equal '1995-11-15T00:00-02:00'
            at Context.eval (webpack-internal:///./test/spec/render/components/util/DateTimeUtil.spec.js:153:149)
       Chrome Headless 109.0.5412.0 (Mac OS 10.15.7) DateTimeUtil #serializeDateTime should serialize with normalized timezone FAILED
        AssertionError: expected '1995-11-13T00:00Z' to equal '1995-11-15T00:00Z'
            at Context.eval (webpack-internal:///./test/spec/render/components/util/DateTimeUtil.spec.js:164:149)
       Chrome Headless 109.0.5412.0 (Mac OS 10.15.7) DateTimeUtil #serializeDateTime should serialize without timezone FAILED
        AssertionError: expected '1995-11-14T00:00' to equal '1995-11-15T00:00'
            at Context.eval (webpack-internal:///./test/spec/render/components/util/DateTimeUtil.spec.js:174:149)
       Chrome Headless 109.0.5412.0 (Mac OS 10.15.7): Executed 433 of 435 (6 FAILED) (skipped 2) (7.777 secs / 6.862 secs)
       TOTAL: 6 FAILED, 427 SUCCESS
       npm ERR! Lifecycle script `test` failed with error: 
       npm ERR! Error: command failed 
       npm ERR!   in workspace: @bpmn-io/form-js-viewer@0.14.1 
       npm ERR!   at location: /Users/guilhermedepaula/git/form-js/packages/form-js-viewer 
 ```

### Expected Behavior

The tests should pass without errors.

### Environment

- Host (Browser/Node version), if applicable: Node v18.16.0
- OS: MacOS Ventura
- Library version: 0.14.1

**Comment by guilhermep** [comment]
I'm in the America/Sao_Paulo time zone (-03:00). I ran some debugging and it indeed seems to be time zone related.

**Comment by pinussilvestrus** [comment]
Thanks for sharing! We will try to have a look, we can't give any timeline though.

**Comment by guilhermep** [comment]
I'll take a deeper look and try to fix this.

**Comment by pinussilvestrus** [comment]
That's really appreciated, thank you! Let us know when you need help :+1:

**Comment by guilhermep** [comment]
I need clarification about the date and time serialization test cases, for instance: 
https://github.com/bpmn-io/form-js/blob/7ebf9d092943e6f55ce69be26338927a385c03db/packages/form-js-viewer/test/spec/render/components/util/DateTimeUtil.spec.js#L343

When I evaluate `new Date('1995-11-15')`, I get `Tue Nov 14 1995 22:00:00 GMT-0200 (Horário de Verão de Brasília)`, local time, which conflicts with the expected output of `1995-11-15T00:00`, suggesting UTC time. 

Despite this, form element dates appear to display in local time, not UTC. 

Could these tests overlook potential discrepancies in the [assumed time zone](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse#differences_in_assumed_time_zone) in the Date constructor? Should we consider the format `new Date('November 15, 1995')` instead?

**Comment by vsgoulart** [comment]
Fixed by https://github.com/bpmn-io/form-js/commit/f79322ff8f48fc6481ffc875adbc7e8f053e22f0
